name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
